trigger caseTrigger5 on Case (before insert, after insert, before update, after update, before delete, after delete, after undelete) {
if(Trigger.isbefore && Trigger.isInsert){
     for(case cs : Trigger.new){
       cs.subject = cs.subject + 'Modified by kiren' + System.now();
     }
}
if(Trigger.isafter && Trigger.isInsert){
List<casecomment> commentlist = new List<casecomment>();
     casecomment cc = new casecomment();
     cc.CommentBody='Autogenerated case by Trigger.isafter';
     cc.ParentId = Trigger.new.get(0).Id ;
     commentlist.add(cc);
     insert commentlist;
}
}